spring:
  application:
    name: saleslens

  batch:
    job:
      enabled: false

  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/saleslens_db}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASS}


  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    listener:
      auto-startup: true
      ack-mode: batch
    consumer:
      group-id: saleslens-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB

  task:
    scheduling:
      thread-name-prefix: "jdbc-scheduler-"
      pool:
        size: 4

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 900000
  refresh-token-expiry: 604800000

server:
  port: 8080

langchain4j:
  ollama:
    chat-model:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      model-name: ${OLLAMA_MODEL_NAME:qwen3.5:9b}

saleslens:
  batch:
    chunk-size: 50
    jdbc:
      poll-interval-ms: 60000
  encryption:
    key: ${ENCRYPTION_KEY:change-me-in-production}
    salt: ${ENCRYPTION_SALT:deadbeefdeadbeef}

#logging:
#  level:
#    org.apache.kafka.clients.consumer: DEBUG
#    org.springframework.kafka: DEBUG